name: Handle New Member Branch

on:
  create:
    branches:
      - 'u/*'

jobs:
  add_member_file_and_create_pr:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/u/')
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GA_PUSH_COMMIT_SECRET }}
          ref: ${{ github.ref }}
      
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Member File
        run: |
          MEMBER_NAME=$(echo ${{ github.ref }} | sed 's|refs/heads/u/||')
          FILE_PATH="people/${MEMBER_NAME}.md"
          mkdir -p $(dirname $FILE_PATH)
          cp template.md $FILE_PATH
          sed -i "s/{{ name }}/${MEMBER_NAME}/g" $FILE_PATH
          sed -i "s/{{ date }}/$(date +'%Y-%m-%d')/g" $FILE_PATH
          git add $FILE_PATH
          git commit -m "Add new member file for ${MEMBER_NAME}"
          git push origin "${{ github.head_ref }}"

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GA_PUSH_COMMIT_SECRET }}
      #     branch: ${{ github.ref }}

      # - name: Create Pull Request
      #   uses: repo-sync/pull-request@v2
      #   with:
      #     source_branch: "${{ github.head_ref }}"
      #     destination_branch: "main"
      #     pr_title: "New member added: $MEMBER_NAME"
      #     pr_body: "Please review the new member file for $MEMBER_NAME."
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
