name: Handle New Member

on:
  push:
    branches:
      - main
    paths:
      - '.github/members/**'

jobs:
  create_branch_and_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create New Branch
        run: |
          NEW_BRANCH="member/${{ github.event.pusher.name }}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH

      - name: Add Member File
        run: |
          FILE_PATH="people/${{ github.event.pusher.name }}.md"
          cp template.md $FILE_PATH
          sed -i 's/{{ name }}/${{ github.event.pusher.name }}/g' $FILE_PATH
          sed -i 's/{{ date }}/${{ github.event.created_at }}/g' $FILE_PATH
          git add $FILE_PATH
          git commit -m "Add new member file for ${{ github.event.pusher.name }}"
          git push origin "member/${{ github.event.pusher.name }}"

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "member/${{ github.event.pusher.name }}"
          destination_branch: "main"
          pr_title: "New member added: ${{ github.event.pusher.name }}"
          pr_body: "Please review the new member file for ${{ github.event.pusher.name }}."
          github_token: ${{ secrets.GITHUB_TOKEN }}
